s = set()
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))
n = input("Enyter you number :")
s.add(int(n))

print(s)
